### ISSUE TITLE
Can I use = value to set @Prop default value ? like this

### ISSUE THREAD

**Issue by akai007** [kaorun343/vue-property-decorator#179] opened 2019-03-07 06:38 UTC
@Prop() readonly title: string = 'default value';
now will throw 
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "title"

**Comment by kaorun343** [comment] 2019-03-10 17:21
@akai007 

No, it's not available to do so.

**Comment by jarekcieslak** [comment] 2019-03-25 16:10
I tried to do something similar and ended up with: 
```@prop({default: 'something') readonly title: string;```

but the problem is that it doesn't do any type checking whatsoever on the default value so this is also possible: 
```@prop({default: 666) readonly title: string;```

**Comment by yarkovaleksei** [comment] 2019-03-25 16:15
> I tried to do something similar and ended up with:
> `@prop({default: 'something') readonly title: string;`
> 
> but the problem is that it doesn't do any type checking whatsoever on the default value so this is also possible:
> `@prop({default: 666) readonly title: string;`

The fact that in brackets is performed only at run time.

**Comment by garyo** [comment] 2019-04-18 14:06
I have the opposite problem (I'm using vue-property-decorator 8.1.0 with vue 2.6.10): I'm trying to do it the way @yarkovaleksei mentions above, but I get a typescript error:
```
69:38 Property 'width' has no initializer and is not definitely assigned in the constructor.
    67 | @Component
    68 | export default class NGL extends Vue {
  > 69 |   @Prop({default: '100vw'}) readonly width: string
       |                                      ^
```
If I assign it a value, the typescript error goes away, but then I get the Vue prop-modification warning.

**Comment by stephantabor** [comment] 2019-04-18 17:07
@garyo you need a non-null assertion operator `!`

```ts
@Prop({default: '100vw'}) readonly width!: string
//                                      ^
```

**Closed** 2019-04-18 18:52 UTC

**Comment by damianof** [comment] 2020-03-18 12:39
Any of you happen to know when trying to access 'this' in the @Prop default it does not work, doe snot seem to reference the Vue instance. I.e. @Prop({ default: this.defaultPlaceHolder })

**Comment by stephantabor** [comment] 2020-03-18 15:09
`this` is not available there. from the Vue docs:

> Note that props are validated before a component instance is created, so instance properties (e.g. data, computed, etc) will not be available inside default or validator functions.

you could just move the variable outside of the Vue component if you don't want to inline it in the prop declaration.

**Comment by damianof** [comment] 2020-04-24 10:15
Thank you @stephantabor
