### ISSUE TITLE
V8.5.0 has serious bugs,

### ISSUE THREAD

**Issue by WangJiangJiaoZi** [kaorun343/vue-property-decorator#324] opened 2020-06-14 04:16 UTC
Yesterday's update 8.5.0 has a serious problem

`import { Component } from 'vue-property-decorator'`

The above code will report an error：

Component is not defined

**Comment by escapedcat** [comment] 2020-06-15 04:35
@WangJiangJiaoZi, this should solve your issue:
`yarn add vue-class-component -D` or `npm i vue-class-component -D`   
It's just a missing dependency nothing really serious.  

I have to admit I was confused as well:
- [Release 8.5.0 is not being listed under releases](https://github.com/kaorun343/vue-property-decorator/releases)
- [Changelog is only listing 8.5.0](https://github.com/kaorun343/vue-property-decorator/blob/master/CHANGELOG.md) is mentioning that `vue-class-component` was moved to peerDependencies. Would this justify a breaking-change maybe to make people aware that their builds might fail?

Anyways, thx for your work @kaorun343 ❤️

**Comment by VerifiedGruber** [comment] 2020-06-15 16:22
> @WangJiangJiaoZi, this should solve your issue:
> `yarn add vue-class-component -D` or `npm i vue-class-component -D`
> It's just a missing dependency nothing really serious.
> 
> I have to admit I was confused as well:
> 
> * [Release 8.5.0 is not being listed under releases](https://github.com/kaorun343/vue-property-decorator/releases)
> * [Changelog is only listing 8.5.0](https://github.com/kaorun343/vue-property-decorator/blob/master/CHANGELOG.md) mentioning that `vue-class-component` was moved to peerDependencies. Would this justify a breaking-change maybe to make people aware that their builds might fail?
> 
> Anyways, thx for your work @kaorun343 ❤️

It's not a lightweight issue. I use [this](https://github.com/vuepress-reco/vuepress-theme-reco) [vuepress](https://github.com/vuejs/vuepress) theme on my [Gitlab Page](https://gitlab.com/pages/vuepress), and just this missing dependency made my whole pipeline fail. I just had to change our policy to commit locking files due to this bug specifically, because I already filter packages based on their dependencies to avoid this kind of issue. It is a care package for a lot of themes out there and it should be expected that will be more complaints once these people try to try to build their pipeline in the next following days. Executing:
`yarn add vue-class-component -D` has fixed the issue temporarily.

**Comment by ldawkes** [comment] 2020-06-15 21:13
> @WangJiangJiaoZi, this should solve your issue:
> `yarn add vue-class-component -D` or `npm i vue-class-component -D`
> It's just a missing dependency nothing really serious.
> 
> I have to admit I was confused as well:
> 
>     * [Release 8.5.0 is not being listed under releases](https://github.com/kaorun343/vue-property-decorator/releases)
> 
>     * [Changelog is only listing 8.5.0](https://github.com/kaorun343/vue-property-decorator/blob/master/CHANGELOG.md) mentioning that `vue-class-component` was moved to peerDependencies. Would this justify a breaking-change maybe to make people aware that their builds might fail?
> 
> 
> Anyways, thx for your work @kaorun343 heart

I'd consider builds failing after a minor version update a breaking change, what was the reason for moving it to `peerDependencies`?

**Comment by Mister-Hope** [comment] 2020-06-16 10:07
I agree this is a huge breaking change too, building failure bothers me too after I run `yarn upgrade`

**Comment by mevludin90** [comment] 2020-06-18 16:06
I ran into this issue today. This is a breaking change.

**Comment by kirschre** [comment] 2020-06-18 20:21
Ran into this today myself. Agreed that this should be considered a breaking change - the packages consumers are required to install are part of the library's contract. @kaorun343 can this change be patched out and released as a major for safety?

**Comment by kaorun343** [comment] 2020-06-18 20:42
I published `v8.5.1` and `v9.0.0`.
- `v8.5.1` : `vue-class-component` is in `dependencies`
- `v9.0.0` : `vue-class-component` is in `peerDependencies`
I apologize you to the breaking change caused by `v8.5.0`.

**Comment by kirschre** [comment] 2020-06-18 20:44
@kaorun343 thank you :smile:

**Closed** 2020-06-20 14:29 UTC
